//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMain
{
    using GameMain.UI;
    
    
    public class TempView : UIView
    {
        
        private UnityEngine.GameObject _gocontent;
        
        private UnityEngine.UI.Image _imghpbar;
        
        private UnityEngine.GameObject _gohpbar;
        
        private TMPro.TextMeshProUGUI _tmphpText;
        
        private UnityEngine.GameObject _gohpText;
        
        public virtual UnityEngine.GameObject gocontent
        {
            get
            {
                return this._gocontent;
            }
            set
            {
                this._gocontent = value;
            }
        }
        
        public virtual UnityEngine.UI.Image imghpbar
        {
            get
            {
                return this._imghpbar;
            }
            set
            {
                this._imghpbar = value;
            }
        }
        
        public virtual UnityEngine.GameObject gohpbar
        {
            get
            {
                return this._gohpbar;
            }
            set
            {
                this._gohpbar = value;
            }
        }
        
        public virtual TMPro.TextMeshProUGUI tmphpText
        {
            get
            {
                return this._tmphpText;
            }
            set
            {
                this._tmphpText = value;
            }
        }
        
        public virtual UnityEngine.GameObject gohpText
        {
            get
            {
                return this._gohpText;
            }
            set
            {
                this._gohpText = value;
            }
        }
    }
}
